name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        ocaml-compiler:
          - 5.5.x
          - 5.4.x
          - 5.3.x
          - 5.2.x
          - 5.1.x
          - 5.0.x
          - 4.14.x
          - 4.13.x
          - 4.12.x
          - 4.11.x
          - ocaml-base-compiler.4.10.2
          - ocaml-base-compiler.4.09.1
          - ocaml-base-compiler.4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          opam-repositories: |
            default: git+https://github.com/ocaml/opam-repository.git
            archive: git+https://github.com/ocaml/opam-repository-archive.git
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest


  lower-bounds-downgrade:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Downgrade dependencies
        run: opam install --solver=builtin-0install --criteria="+removed,+count[version-lag,solution]" . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest


  opam-install:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install with test
        run: opam install ppx_deriving_hash --with-test
